pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SupportedLanguage {
    Chinese,
    ChineseYue,
    English,
    Arabic,
    Russian,
    Spanish,
    French,
    Portuguese,
    German,
    Turkish,
    Dutch,
    Ukrainian,
    Vietnamese,
    Indonesian,
    Japanese,
    Italian,
    Korean,
    Thai,
    Polish,
    Romanian,
    Greek,
    Czech,
    Finnish,
    Hindi,
    Bulgarian,
    Danish,
    Hebrew,
    Malay,
    Persian,
    Slovak,
    Swedish,
    Croatian,
    Filipino,
    Hungarian,
    Norwegian,
    Slovenian,
    Catalan,
    Nynorsk,
    Tamil,
    Afrikaans,
    Auto,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for SupportedLanguage {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Chinese => serializer.serialize_str("Chinese"),
            Self::ChineseYue => serializer.serialize_str("Chinese,Yue"),
            Self::English => serializer.serialize_str("English"),
            Self::Arabic => serializer.serialize_str("Arabic"),
            Self::Russian => serializer.serialize_str("Russian"),
            Self::Spanish => serializer.serialize_str("Spanish"),
            Self::French => serializer.serialize_str("French"),
            Self::Portuguese => serializer.serialize_str("Portuguese"),
            Self::German => serializer.serialize_str("German"),
            Self::Turkish => serializer.serialize_str("Turkish"),
            Self::Dutch => serializer.serialize_str("Dutch"),
            Self::Ukrainian => serializer.serialize_str("Ukrainian"),
            Self::Vietnamese => serializer.serialize_str("Vietnamese"),
            Self::Indonesian => serializer.serialize_str("Indonesian"),
            Self::Japanese => serializer.serialize_str("Japanese"),
            Self::Italian => serializer.serialize_str("Italian"),
            Self::Korean => serializer.serialize_str("Korean"),
            Self::Thai => serializer.serialize_str("Thai"),
            Self::Polish => serializer.serialize_str("Polish"),
            Self::Romanian => serializer.serialize_str("Romanian"),
            Self::Greek => serializer.serialize_str("Greek"),
            Self::Czech => serializer.serialize_str("Czech"),
            Self::Finnish => serializer.serialize_str("Finnish"),
            Self::Hindi => serializer.serialize_str("Hindi"),
            Self::Bulgarian => serializer.serialize_str("Bulgarian"),
            Self::Danish => serializer.serialize_str("Danish"),
            Self::Hebrew => serializer.serialize_str("Hebrew"),
            Self::Malay => serializer.serialize_str("Malay"),
            Self::Persian => serializer.serialize_str("Persian"),
            Self::Slovak => serializer.serialize_str("Slovak"),
            Self::Swedish => serializer.serialize_str("Swedish"),
            Self::Croatian => serializer.serialize_str("Croatian"),
            Self::Filipino => serializer.serialize_str("Filipino"),
            Self::Hungarian => serializer.serialize_str("Hungarian"),
            Self::Norwegian => serializer.serialize_str("Norwegian"),
            Self::Slovenian => serializer.serialize_str("Slovenian"),
            Self::Catalan => serializer.serialize_str("Catalan"),
            Self::Nynorsk => serializer.serialize_str("Nynorsk"),
            Self::Tamil => serializer.serialize_str("Tamil"),
            Self::Afrikaans => serializer.serialize_str("Afrikaans"),
            Self::Auto => serializer.serialize_str("auto"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for SupportedLanguage {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "Chinese" => Ok(Self::Chinese),
            "Chinese,Yue" => Ok(Self::ChineseYue),
            "English" => Ok(Self::English),
            "Arabic" => Ok(Self::Arabic),
            "Russian" => Ok(Self::Russian),
            "Spanish" => Ok(Self::Spanish),
            "French" => Ok(Self::French),
            "Portuguese" => Ok(Self::Portuguese),
            "German" => Ok(Self::German),
            "Turkish" => Ok(Self::Turkish),
            "Dutch" => Ok(Self::Dutch),
            "Ukrainian" => Ok(Self::Ukrainian),
            "Vietnamese" => Ok(Self::Vietnamese),
            "Indonesian" => Ok(Self::Indonesian),
            "Japanese" => Ok(Self::Japanese),
            "Italian" => Ok(Self::Italian),
            "Korean" => Ok(Self::Korean),
            "Thai" => Ok(Self::Thai),
            "Polish" => Ok(Self::Polish),
            "Romanian" => Ok(Self::Romanian),
            "Greek" => Ok(Self::Greek),
            "Czech" => Ok(Self::Czech),
            "Finnish" => Ok(Self::Finnish),
            "Hindi" => Ok(Self::Hindi),
            "Bulgarian" => Ok(Self::Bulgarian),
            "Danish" => Ok(Self::Danish),
            "Hebrew" => Ok(Self::Hebrew),
            "Malay" => Ok(Self::Malay),
            "Persian" => Ok(Self::Persian),
            "Slovak" => Ok(Self::Slovak),
            "Swedish" => Ok(Self::Swedish),
            "Croatian" => Ok(Self::Croatian),
            "Filipino" => Ok(Self::Filipino),
            "Hungarian" => Ok(Self::Hungarian),
            "Norwegian" => Ok(Self::Norwegian),
            "Slovenian" => Ok(Self::Slovenian),
            "Catalan" => Ok(Self::Catalan),
            "Nynorsk" => Ok(Self::Nynorsk),
            "Tamil" => Ok(Self::Tamil),
            "Afrikaans" => Ok(Self::Afrikaans),
            "auto" => Ok(Self::Auto),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for SupportedLanguage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Chinese => write!(f, "Chinese"),
            Self::ChineseYue => write!(f, "Chinese,Yue"),
            Self::English => write!(f, "English"),
            Self::Arabic => write!(f, "Arabic"),
            Self::Russian => write!(f, "Russian"),
            Self::Spanish => write!(f, "Spanish"),
            Self::French => write!(f, "French"),
            Self::Portuguese => write!(f, "Portuguese"),
            Self::German => write!(f, "German"),
            Self::Turkish => write!(f, "Turkish"),
            Self::Dutch => write!(f, "Dutch"),
            Self::Ukrainian => write!(f, "Ukrainian"),
            Self::Vietnamese => write!(f, "Vietnamese"),
            Self::Indonesian => write!(f, "Indonesian"),
            Self::Japanese => write!(f, "Japanese"),
            Self::Italian => write!(f, "Italian"),
            Self::Korean => write!(f, "Korean"),
            Self::Thai => write!(f, "Thai"),
            Self::Polish => write!(f, "Polish"),
            Self::Romanian => write!(f, "Romanian"),
            Self::Greek => write!(f, "Greek"),
            Self::Czech => write!(f, "Czech"),
            Self::Finnish => write!(f, "Finnish"),
            Self::Hindi => write!(f, "Hindi"),
            Self::Bulgarian => write!(f, "Bulgarian"),
            Self::Danish => write!(f, "Danish"),
            Self::Hebrew => write!(f, "Hebrew"),
            Self::Malay => write!(f, "Malay"),
            Self::Persian => write!(f, "Persian"),
            Self::Slovak => write!(f, "Slovak"),
            Self::Swedish => write!(f, "Swedish"),
            Self::Croatian => write!(f, "Croatian"),
            Self::Filipino => write!(f, "Filipino"),
            Self::Hungarian => write!(f, "Hungarian"),
            Self::Norwegian => write!(f, "Norwegian"),
            Self::Slovenian => write!(f, "Slovenian"),
            Self::Catalan => write!(f, "Catalan"),
            Self::Nynorsk => write!(f, "Nynorsk"),
            Self::Tamil => write!(f, "Tamil"),
            Self::Afrikaans => write!(f, "Afrikaans"),
            Self::Auto => write!(f, "auto"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
